// <auto-generated />
namespace EventFinder_GC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class paypal_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paypal_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202001242000052_paypal_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
