// <auto-generated />
namespace EventFinder_GC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newMigration));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:EventFinder_GC/Migrations/202001222215517_newMigration.Designer.cs
            get { return "202001222215517_newMigration"; }
=======
            get { return "202001222140537_newMigration"; }
>>>>>>> 76254ba1ee65f4d06621ec14fbe5d9be7787eb70:EventFinder_GC/Migrations/202001222140537_newMigration.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
