// <auto-generated />
namespace EventFinderAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialTabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialTabel));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221620298_InitialTabel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
