// <auto-generated />
namespace EventFinderAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:EventFinderAPI/EventFinderAPI/Migrations/202001222220533_newMigration.Designer.cs
    public sealed partial class newMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202001222220533_newMigration"; }
=======
    public sealed partial class InitialTabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialTabel));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221620298_InitialTabel"; }
>>>>>>> 76254ba1ee65f4d06621ec14fbe5d9be7787eb70:EventFinderAPI/EventFinderAPI/Migrations/202001221620298_InitialTabel.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
