// <auto-generated />
namespace EventFinder_GC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:EventFinderAPI/EventFinderAPI/Migrations/202001232136050_ImagePathAddition.Designer.cs
    public sealed partial class ImagePathAddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImagePathAddition));
        
        string IMigrationMetadata.Id
        {
            get { return "202001232136050_ImagePathAddition"; }
=======
    public sealed partial class addNewProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewProp));
        
        string IMigrationMetadata.Id
        {
            get { return "202001241626092_addNewProp"; }
>>>>>>> 7fa23fe3334ff931c183860b60fb3d1fc1d4c495:EventFinder_GC/Migrations/202001241626092_addNewProp.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
