// <auto-generated />
namespace EventFinderAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:EventFinderAPI/EventFinderAPI/Migrations/202001231404244_seedEventTable.Designer.cs
    public sealed partial class seedEventTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedEventTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001231404244_seedEventTable"; }
=======
    public sealed partial class SeedingEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedingEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221634124_SeedingEvents"; }
>>>>>>> 76254ba1ee65f4d06621ec14fbe5d9be7787eb70:EventFinderAPI/EventFinderAPI/Migrations/202001221634124_SeedingEvents.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
